spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          searchLocations:
            - classpath:config/core/{application}
            - classpath:config/stat/{application}
            - classpath:config/infra/{application}
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

eureka:
  instance:
    preferIpAddress: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
server:
  port: 8888