services:
  stats-server:
    build: stat/stat-server
    container_name: stat-server
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stats
      - SPRING_DATASOURCE_USERNAME=stat
      - SPRING_DATASOURCE_PASSWORD=stat

  stats-db:
    image: postgres:16.1
    container_name: postgres-ewm-stats-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_PASSWORD=stat
      - POSTGRES_USER=stat
      - POSTGRES_DB=ewm-stats

  ewm-service:
    build:
      context: main-service
      dockerfile: Dockerfile
    image: ewm-service-image
    container_name: ewm-service
    depends_on:
      - ewm-db
      - stats-server
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-main
      - SPRING_DATASOURCE_USERNAME=service
      - SPRING_DATASOURCE_PASSWORD=service

  ewm-db:
    image: postgres:16.1
    container_name: postgres-ewm-service-db
    ports:
      - "6543:5432"
    environment:
      - POSTGRES_PASSWORD=service
      - POSTGRES_USER=service
      - POSTGRES_DB=ewm-main