services:

  stats-db:
    image: postgres:16.1
    container_name: postgres-ewm-stats-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_PASSWORD=stat
      - POSTGRES_USER=stat
      - POSTGRES_DB=ewm-stats

  ewm-db:
    image: postgres:16.1
    container_name: postgres-ewm-service-db
    ports:
      - "6543:5432"
    environment:
      - POSTGRES_PASSWORD=service
      - POSTGRES_USER=service
      - POSTGRES_DB=ewm-main