# Application Basic Info
application.name=collector
server.port=8187
# gRPC Server Configuration
grpc.server.port=14301
grpc.server.address=172.18.0.14
grpc.server.plaintext=true

# Kafka Configuration
kafka.bootstrap-servers=kafka:29092
kafka.action-topic=stats.user-actions.v1
kafka.similarity-topic=stats.events-similarity.v1
kafka.consumer.auto-offset-reset=latest
kafka.auto-commit=true