# Application identifier
application.name=aggregator

# gRPC server port - auto-assign
grpc.server.port=0

# Kafka configuration
kafka.bootstrap-servers=localhost:9092
kafka.group-id=action-group
kafka.action-topic=stats.user-actions.v1
kafka.similarity-topic=stats.events-similarity.v1
kafka.auto-commit=true