# Application Basic Info
application.name=aggregator

# gRPC Server Configuration
grpc.server.port=8189

# Kafka Configuration
kafka.bootstrap-servers=kafka:29092
kafka.action-topic=stats.user-actions.v1
kafka.similarity-topic=stats.events-similarity.v1
kafka.auto-commit=true
kafka.group-id=action-group