DROP TABLE IF EXISTS events CASCADE;

CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    annotation VARCHAR(2000) NOT NULL CHECK (length(annotation) >= 20 AND length(annotation) <= 2000),
    category_id BIGINT,
    description VARCHAR(7000) NOT NULL CHECK (length(description) >= 20 AND length(description) <= 7000),
    event_date TIMESTAMP NOT NULL,

    location_lat FLOAT NOT NULL,
    location_lon FLOAT NOT NULL,

    paid BOOLEAN DEFAULT FALSE,
    participant_limit INT DEFAULT 0,
    request_moderation BOOLEAN DEFAULT TRUE,
    title VARCHAR(120) NOT NULL CHECK (length(title) >= 3 AND length(title) <= 120),
    created_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    initiator_id BIGINT,
    published_on TIMESTAMP,
    state SMALLINT NOT NULL
);
