# gRPC Server Configuration
grpc.server.port=8188
grpc.server.plaintext=true
server.ssl.enabled=false

# gRPC Client Configuration
grpc.client.enable-plaintext=true

# Application Basic Info
application.name=analyzer

# DataSource Configuration
spring.datasource.url=jdbc:postgresql://analyzer-db:5432/analyzer_server
spring.datasource.username=analyzer
spring.datasource.password=analyzer
spring.datasource.driverClassName=org.postgresql.Driver

# Hibernate/JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.jdbc.time_zone=UTC

# Kafka Configuration
kafka.bootstrap-servers=kafka:29092
kafka.group-id=action-group
kafka.action-topic=stats.user-actions.v1
kafka.similarity-topic=stats.events-similarity.v1
kafka.auto-commit=true