# Application identifier
application.name=analyzer

# gRPC server port - auto-assign
grpc.server.port=0

# DataSource configuration
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:6542/analyzer_server
spring.datasource.username=analyzer
spring.datasource.password=analyzer

# Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.jdbc.time_zone=UTC

# Kafka configuration
kafka.bootstrap-servers=localhost:9092
kafka.group-id=action-group
kafka.action-topic=stats.user-actions.v1
kafka.similarity-topic=stats.events-similarity.v1
kafka.auto-commit=false