# Application Settings
application.name=event-service
application.date-time-format=yyyy-MM-dd HH:mm:ss

# Spring Boot Settings
spring.main.banner-mode=OFF

# Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.format_sql=true
spring.jpa.jdbc.time_zone=UTC

# DataSource Settings
spring.sql.init.mode=always
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:6546/event_service
spring.datasource.username=event
spring.datasource.password=event

# gRPC Client Configurations
grpc.client.analyzer.address=discovery:///analyzer
grpc.client.analyzer.enableKeepAlive=true
grpc.client.analyzer.keepAliveWithoutCalls=true
grpc.client.analyzer.negotiationType=plaintext

grpc.client.collector.address=discovery:///collector
grpc.client.collector.enableKeepAlive=true
grpc.client.collector.keepAliveWithoutCalls=true
grpc.client.collector.negotiationType=plaintext

# Management Endpoints Exposure
management.endpoints.web.exposure.include=*

# Logging Levels
logging.level.org.springframework.orm.jpa=WARN
logging.level.org.springframework.orm.jpa.JpaTransactionManager=WARN
logging.level.org.springframework.transaction=WARN
logging.level.org.springframework.transaction.interceptor=WARN

# Server Ports (auto-allocated)
server.port=0
grpc.server.port=0